name: Build

on:
  push:
    branches:
      - main     

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      MONGODB_URI_PROD: ${{ secrets.MONGODB_URI_PROD }}
      MONGODB_URI_DEV: ${{ secrets.MONGODB_URI_DEV }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci   # safer + installs devDependencies

      - name: Build Next.js app
        run: npm run build
        env:
          NODE_ENV: production   # only set for build step
